[project]
name = "colqwen-serverless-lkpp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "byaldi>=0.0.7",
    "huggingface-hub>=0.27.0",
    "ipykernel>=6.29.5",
    "pip>=24.3.1",
    "runpod>=1.7.7",
]
